[viewport]
maximum_width = 26

[netres]
limit = 25.0

[game]
map_pool = "LPPMapPool"
soft_max_players = "111"
lobbyenabled = true
panic_bunker.min_account_age = 1440
#panic_bunker.min_overall_hours = 0

[server]
rules_file = "LPPRulesetNon"

[rules]
time = 60.0

[infolinks]
discord = "https://wiki.legacyofparadise.space/discord"
github = "https://github.com/Legacy-Of-Paradise/main-nonerp"
wiki = "http://wiki.legacyofparadise.space/"
website = "https://boosty.to/legacy-of-paradise"

[vote]
restart_required_ratio = 0.85
same_type_timeout = 300.0
timerrestart = 30
map_enabled = true
preset_enabled = true
restart_enabled = true

[hub]
advertise = true
tags = "lang:ru,region:eu_e,rp:med"

[shuttle]
auto_call_time = 90
arrivals = true
arrivals_planet = false
emergency_early_launch_allowed = true

[admin]
see_own_notes = true

[ahelp]
admin_prefix = true
admin_prefix_webhook = true

[discord]
rich_main_icon_id = "https://bit.ly/lopicon"
