 - type: job
   id: LPPSecurityEngineer
   name: job-name-security-enginer
   description: job-description-security-enginer
   playTimeTracker: LPPJobSecurityEnginer
   requirements:
     - !type:DepartmentTimeRequirement
       department: Security
       time: 36000
     - !type:DepartmentTimeRequirement
       department: Engineering
       time: 72000
   startingGear: LPPSecurityEngineerGear
   icon: "LPPJobIconSecurityEnginer"
   supervisors: job-supervisors-hos
   canBeAntag: false
   access:
   - Security
 #  - Brig
   - Maintenance
   - External
   - Engineering
   special:
   - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]

 - type: startingGear
   id: LPPSecurityEngineerGear
   equipment:
     jumpsuit: LPPClothingUniformJumpsuitSecEngineer
     shoes: LPPClothingShoesBootsJackSecEnginer
     eyes: LPPClothingEyesHudSecEng
     gloves: ClothingHandsGlovesColorYellow
     head: ClothingHeadHatHardhatYellow
     id: LPPSecurityEngineerPDA
     outerClothing: ClothingOuterVestHazard
     ears: LPPClothingHeadsetSecurityEngineer
     belt: LPPClothingMilitaryWebbingSecEng
     back: LPPClothingBackpackSecurityEngineer
   storage:
     back:
     - SheetSteel10
     - SheetGlass10
     - LPPC4Low
